apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eso-secret-store
  namespace: {{ include "eso-secrets-sync.namespace" . }}
  labels:
    {{- include "eso-secrets-sync.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.provider.gcp.projectID }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.provider.gcp.authSecretName }}
