apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: eso-secret-store
  namespace: {{ include "eso-secrets-sync.namespace" . }}
  labels:
    {{- include "eso-secrets-sync.labels" . | nindent 4 }}

spec:
  provider:
    {{- if eq .Values.provider.type "gcp" }}
    gcpsm:
      projectID: {{ .Values.provider.gcp.projectID }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.provider.gcp.authSecretName }}

    {{- else if eq .Values.provider.type "aws" }}
    aws:
      service: SecretsManager
      region: {{ .Values.provider.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.provider.aws.serviceAccountName }}

    {{- else if eq .Values.provider.type "vault" }}
    vault:
      server: {{ .Values.provider.vault.server }}
      path: {{ .Values.provider.vault.path }}
      version: {{ .Values.provider.vault.version }}
      auth:
        {{- if .Values.provider.vault.tokenSecretRef }}
        tokenSecretRef:
          name: {{ .Values.provider.vault.tokenSecretRef.name }}
          key: {{ .Values.provider.vault.tokenSecretRef.key }}
          namespace: {{ .Values.provider.vault.tokenSecretRef.namespace }}
        {{- else if .Values.provider.vault.kubernetes }}
        kubernetes:
          mountPath: {{ .Values.provider.vault.kubernetes.mountPath }}
          role: {{ .Values.provider.vault.kubernetes.role }}
        {{- end }}

    {{- else }}
    {{- fail "provider.type must be one of: gcp, aws, vault" }}
    {{- end }}
